name: Build Windows App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: 安装Microsoft Visual C++ Redistributable
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vc_redist.x64.exe -OutFile vc_redist.x64.exe
          Start-Process -FilePath .\vc_redist.x64.exe -ArgumentList '/quiet', '/norestart' -Wait

      - name: 构建应用
        run: |
          pyinstaller --clean --noconfirm --onedir --windowed --add-data "src/frontend;src/frontend" --icon=app_icon.ico main.py

      - name: 创建发布包
        run: |
          cd dist
          Compress-Archive -Path main/* -DestinationPath ../getorder_app_windows.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: getorder-app-windows
          path: getorder_app_windows.zip
